# Configuration file for the Excavator and Motion Platform Data Exchange System

# Server settings
server:
  host: '192.168.0.131'  # Listen on all available network interfaces
  #host: 'localhost'  # Listen only on the local machine
  port: 8000  # The port number the server will use

# List of clients (devices) that will exchange data
clients:
  excavator:
    "num_outputs": 31  # Number of control values to send
  motion_platform:
    "num_outputs": 20  # Number of control values to send
